name: $SCONE_CONFIG_ID
version: "0.3"

services:
  - name: api_service
    image_name: python_image
    command: /venv/bin/python3 /app/app.py
    mrenclaves: [$MRENCLAVE]
    fspf_path: /fspf/fspf.pb
    fspf_key: $FSPF_KEY
    fspf_tag: $FSPF_TAG
    environment:
      PLAIN_HTTP: $PLAIN_HTTP
      SERVER_PORT: $SERVER_PORT
      SYSTEM_ID: $SYSTEM_ID
      INCLUDE_USAGE_STATISTICS: $INCLUDE_USAGE_STATISTICS
      USAGE_STATISTICS_MAX_SAMPLES: $USAGE_STATISTICS_MAX_SAMPLES
      AUTH_USERNAME: $AUTH_USERNAME
      AUTH_PASSWORD: $AUTH_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD

security:
  attestation:
    tolerate:
      [
        debug-mode,
        hyperthreading,
        outdated-tcb,
        insecure-igpu,
        software-hardening-needed,
        insecure-configuration,
      ]
    ignore_advisories: "*"
